apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  type: LoadBalancer
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
  - port: 9300
    name: "9300"
  selector:
    io.kompose.service: elasticsearch
